# sudo apt install tmuxinator
name: ROVER
root: ~/URC
windows:
  -  TX1: cat README.md; cat rosws/README.md
  -  TOP: 
      layout: tiled
      panes:
        - top
        - htop
        - dmesg -w
        - watch "./scripts/print_cpu_temp.sh; df -h"
  - CORE: 
      layout: even-horizontal
      panes:
        - python rosws/src/rover/src/lost_comms_recovery.py --ip 192.168.137.19
        - roslaunch rover lost_comms_recovery.launch
        - roscore
  - GPS:
      root: ~/URC/rosws/src/rover/
      layout: even-horizontal
      panes:
        - sleep 5; roslaunch rover gps.launch dev:=/dev/ttyTHS2
        - sleep 3; rostopic echo /gps/fix
        - sleep 3; rostopic echo /gps/filtered
  # - IMU:
  #     root: ~/URC/rosws/src/rtimulib_ros/
  #     layout: even-horizontal
  #     panes:
  #       - sleep 6; roslaunch rtimulib_ros rtimulib_ros.launch
  #       - sleep 3; rostopic echo imu/data_raw
  #       - sleep 6; roslaunch /home/ubuntu/URC/devstuff/dan/IMU/imu_madgwick_filter.launch
  #       - sleep 3; rostopic echo /imu/data_madg
  - RTAB:
      root: ~/URC/rosws/src/rover_navigation/
      layout: tiled
      panes:
        - sleep 5; roslaunch rover_navigation rtabmap.launch
        - "#sleep 5; roslaunch rover_rtabmap_config obstacle_up.launch"
        - sleep 5; rostopic echo /cmd_vel_mux/move_base
        - sleep 5; rostopic echo /move_base/status
        - sleep 5; roslaunch rover_navigation move_base.launch
  - ZED:
      root: ~/URC/rosws/src/rover/
      layout: even-horizontal
      panes:
        - sleep 5; roslaunch rover zed_up.launch
        - sleep 4; roslaunch rover_navigation rgbd_odometry.launch
#  - EKF:
#      root: ~/URC/rosws/src/rover_robot_localization/
#      layout: tiled
#      panes:
#        - sleep 4; roslaunch rover_robot_localization global_ekf.launch
#        - sleep 3; rostopic echo /odometry/filtered_global
#        - sleep 3; rostopic echo /gps/filtered
#        - sleep 3; rosrun tf tf_echo odom robot_base
  - DRIVE:
      root: ~/URC/rosws/src/rover_drive/
      layout: tiled
      panes:
        - "#roslaunch rover_drive drive.launch dev:=/dev/serial/by-id/usb-Arduino_Srl_Arduino_Mega_85535303636351416262-if00"
        - "#roslaunch rover_teleoperation drive_teleoperation.launch dev:=/dev/input/js0"
        - pio device list
        - sleep 5; rostopic echo cmd_vel
        - sleep 5; rostopic echo cmd_vel_tank
  - ARM:
      root: ~/URC/rosws/src/rover_arm/
      layout: tiled
      panes:
        - "#rosrun rover_arm simple_arm_serial.py"
  # - SCI:
  #     root: ~/URC/rosws/src/rover_science/
  #     layout: tiled
  #     panes:
  #       - 
  #       - python ~/URC/devstuff/components/ImageOverlay/overlay_scale_and_compass.py
  #       - sleep 3; rosrun rover_science save_temp.py _description:=site1
  #       - sleep 3; rosrun rover_science save_ph.py _description:=site1
  #       - watch cat *_temperature.txt
  #       - watch cat *_ph.txt
  - WEBCAMS:
      root: ~/URC/rosws/src/rover/
      layout: main-horizontal
      panes:
        - sleep 4; roslaunch rover usb_webcams.launch
        - v4l2-ctl --list-devices
  - D:
  - M:
  - A:
  - H:

